application: gdgmbale
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: favicon\.ico
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /javascripts
  static_dir: javascripts


- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.1"
